# Generated by Django 4.2.4 on 2023-08-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=30, unique=True)),
                ('job_description', models.TextField()),
                ('payment', models.FloatField()),
                ('job_duration', models.IntegerField()),
                ('start_date', models.DateField()),
                ('image', models.CharField(max_length=200)),
                ('job_category', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('job_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workStudy.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
