# Generated by Django 4.2.4 on 2023-08-19 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("goal", models.IntegerField()),
                ("amount_gained", models.IntegerField(default=0)),
                ("status", models.CharField(default="In Progress", max_length=10)),
                ("slug", models.SlugField(unique=True)),
                ("event_datetime", models.DateTimeField()),
            ],
        ),
    ]
