# Generated by Django 4.2.4 on 2023-08-19 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("event_description", models.TextField()),
                ("type", models.TextField()),
                ("event_duration", models.IntegerField()),
                ("attendees", models.IntegerField(default=0)),
                ("event_date", models.DateField()),
                ("event_start_time", models.TimeField()),
                ("status", models.CharField(default="Upcoming", max_length=10)),
                ("slug", models.SlugField(unique=True)),
                ("date_created", models.DateTimeField()),
            ],
        ),
    ]
